projekatDrugi/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutPage, name="logout")
]

projekatDrugi/filmovi/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'film'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.listaFilmova, name="lista"),

    path('create/', views.createMovie, name="create"),
    path('update/<int:film_id>/', views.updateMovie, name="update"),
    path('delete/<int:film_id>/', views.deleteMovie, name="delete")
]

projekatDrugi/projekatDrugi/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from filmovi import views as lista

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lista.listaFilmova),
    path('about/', views.about),
    path('filmovi/', include('filmovi.urls')),
    path('accounts/', include('accounts.urls'))

]
urlpatterns += staticfiles_urlpatterns()

projekatDrugi/accounts/models.py
from django.db import models

# Create your models here.

projekatDrugi/filmovi/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Film(models.Model):
    naziv = models.CharField(max_length=50)
    ocena = models.IntegerField(max_length=10)
    godina = models.IntegerField()
    kreiraoJe = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.naziv

    #python manage.py makemigrations
    #python manage.py migrate

projekatDrugi/filmovi/forms.py
from django import forms
from . import models

class KreirajFilm(forms.ModelForm):
    class Meta:
        model = models.Film
        fields =['naziv', 'ocena', 'godina']

projekatDrugi/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.
def registerPage(request):
    #form = UserCreationForm()
    if request.method == 'POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('film:lista')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/register.html', {'form':form})

def loginPage(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('film:lista')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logoutPage(request):
    if request.method == 'POST':
        logout(request)
        return redirect('film:lista')

projekatDrugi/filmovi/views.py
from django.shortcuts import render, redirect

from .forms import KreirajFilm
from .models import Film
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def listaFilmova(request):
    lista = Film.objects.all().order_by('godina')
    return render(request, 'filmovi/lista.html', {'lista': lista})

@login_required(login_url="/accounts/login/")
def createMovie(request):
    if request.method == 'POST':
        form = forms.KreirajFilm(request.POST)
        if form.is_valid():
            #sacuvaj
            instance = form.save(commit=False)
            instance.kreiraoJe = request.user
            instance.save()
            return redirect('film:lista')
    else:
        form = forms.KreirajFilm()
    return render(request, 'filmovi/create.html', {'form': form })

@login_required(login_url="/accounts/login/")
def updateMovie(request, film_id):
    film = Film.objects.get(id = film_id)
    form = KreirajFilm(instance = film)
    if request.method == 'POST':
        form = KreirajFilm(request.POST, instance=film)
        if form.is_valid():
            form.save()
            return redirect('film:lista')
        else:
            print(ValueError)
    return render(request, 'filmovi/update.html', {'form': form, 'film_id': film_id })

@login_required(login_url="/accounts/login/")
def deleteMovie(request, film_id):
    film = Film.objects.get(id=film_id)

    if request.method == 'POST':
        film.delete()
        return redirect('film:lista')

    return render(request, 'filmovi/delete.html', {'form': film, 'film_id': film_id})

projekatDrugi/projekatDrugi/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    #return HttpResponse('Home')
    return render(request, 'home.html')

def about(request):
    #return HttpResponse('About page')
    return render(request, 'about.html')

projekatDrugi/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block login %}

    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

projekatDrugi/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block login %}

    <h1>Register</h1>
    <form class="site-form" action="{% url 'accounts:register' %}" method="post">
    {% csrf_token %}
    {{ form }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

projekatDrugi/filmovi/templates/filmovi/create.html
{% extends 'base.html'%}

{% block content %}

    <div class="create-movie">
        <h2>Kreiraj film</h2>
        <form class="site-form" action="{% url 'film:create' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Kreiraj film">
        </form>
    </div>

{% endblock %}

projekatDrugi/filmovi/templates/filmovi/delete.html
{% extends 'base.html'%}

{% block content %}

    <div class="update-movie">
        <h2>Obrisi film</h2>
        <form class="site-form" action="{% url 'film:delete' film_id %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Obrisi film">
        </form>
    </div>

{% endblock %}

projekatDrugi/filmovi/templates/filmovi/lista.html
{% extends 'base.html' %}

{% block content %}
        <h1>Lista filmova</h1>
        <div class="lista">
            {% for film in lista %}
            <div class="film">
            <h2>{{film.naziv}}</h2>
            <p>{{film.godina}}</p>
            <p>{{film.ocena}}</p>
            <button type="submit"><a href="{% url 'film:update' film.id%}">Odvedi do apdejtovanja</a></button>
            <button type="submit"><a href="{% url 'film:delete' film.id%}">Odvedi do brisanja</a></button>
            </div>
            {% endfor %}
            <button type="submit"><a href="{% url 'film:create' %}">Odvedi do kreiranja</a></button>
        </div>
{% endblock %}

projekatDrugi/filmovi/templates/filmovi/update.html
{% extends 'base.html'%}

{% block content %}

    <div class="update-movie">
        <h2>Apdejtuj film</h2>
        <form class="site-form" action="{% url 'film:update' film_id %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Apdejtuj film">
        </form>
    </div>

{% endblock %}

projekatDrugi/templates/about.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Despot</title>
</head>
<body>
<h1>About stranica</h1>
<p1>Dobrodosli na about stranicu</p1>
</body>
</html>

projekatDrugi/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Despot</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <div class="wrapper">
            <h1><a href="{% url 'film:lista' %}">Vrati listu filmova</a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class = "logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
{#                        <li><a href="{% url 'film:create' %}">Kreiraj film</a></li>#}
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:register' %}">Register</a></li>
                    {% endif %}
                </ul>
            </nav>
        {% block login %}
        {% endblock %}
        {% if user.is_authenticated %}
            {% block content %}
            {% endblock %}
        {% endif %}
        </div>
    </body>
</html>

projekatDrugi/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Despot</title>
</head>
<body>
<h1>Home stranica</h1>
<p1>Dobrodosli na home stranicu</p1>
</body>
</html>